name: Dev Build

on:
  push:
    branches: 
      - dev

jobs:
  build:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Build with Gradle
      run: ./gradlew cleanCache clean setupCrucible --refresh-dependencies 

    - name: Show debug info
      run: ./gradlew --version 
      
    - name: Create distribution
      run: ./gradlew jar
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Compress
      run: tar -cvf build.tar *
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Crucible Artifact
        path: build.tar
